name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ANDROID_COMPILE_SDK: "29"  # Android 10
      ANDROID_BUILD_TOOLS: "29.0.3"
      ANDROID_MIN_SDK: "28"      # Android 9

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Build APK
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug -PtargetSdk=$ANDROID_COMPILE_SDK -PminSdk=$ANDROID_MIN_SDK

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: alpha-tester
          path: app/build/outputs/apk/debug/app-debug.apk
